### ISSUE TITLE
How do you add your keys?

### ISSUE THREAD

**Issue by nathan-nz** [tytydraco/SSH#2]
It could be I'm a bit thick, but I can't see how to add my SSH keys to the app.

I have disabled password authentication on my servers, so need key access to work.

Love how it is so minimalist! Hope I can get it to work.

**Comment by tytydraco** [comment]
Hi! Thanks :)

Basically the app itself creates a SSH key internally. Click the little "copy button" to copy the RSA public key and add that as a known key to your server. 

Hope that works!

**Comment by nathan-nz** [comment]
Ah - got it. I wondered how it got a public key in the first place. Totally
makes sense!

Keep up the great work!
